### ISSUE TITLE
Monospaced fonts in arabic

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#117]
Assuming i have correctly understood it, the TTML IMSC spec seems to be guiding content authors to use monospaced, rather than proportionally-spaced, fonts for arabic – which to me seems to be backwards.

Could you please look at https://github.com/w3c/i18n-activity/issues/415 and let me know whether you think what i'm saying makes sense?

**Comment by behnam** [comment]
I don't understand the rational behind having anything about font style special-cased for Hebrew and Arabic. I believe any such ruling needs some explanation in the first place.

Although not giving the best results, monospace typefaces for Perso-Arabic script are readable enough for common use-cases. But, of course, proportional typefaces could result in much better aesthetics and legibility.

**Comment by behnam** [comment]
But, @r12a, besides what you mentioned already, I should say I'm surprised by some other i18n decisions in that document.

Under Section 9.5 Paint Text:

> NOTE
> While one-to-one mapping between characters and typographical glyphs is generally the rule in some scripts, e.g. latin script, it is the exception in others. For instance, in arabic script, a character can yield multiple glyphs depending on its position in a word. The Hypothetical Render Model always assumes a one-to-one mapping, but reduces the performance of the glyph buffer for scripts where one-to-one mapping is not the general rule (see GCpy below).

IMHO, that's a 20th century approach and the non-one-to-one mapping case is true for many other writing systems, besides Arabic, like Indic writing systems.

(Also, editorial note about names of languages/writing-systems not being capitalized.)

Later, under Section B. Recommended Character Sets, a few languages are hand-picked without providing rational for it. Also:
1. How can we add more languages (and their character set) to the this list?
2. What are the criteria in creating the character set for a languages.
