### ISSUE TITLE
Create a section Arabic Script Overview

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#12]
While working on the Tibetan layout requirements doc at http://w3c.github.io/tlreq/ it seemed useful to separate out the information that simply described how the script worked into a separate section, Tibetan script overview.  The actual layout requirements start in the following section, Typography for Tibetan Characters.

i suspect that a similar Arabic Script Overview section could be useful to gather together descriptive text for alreq.

**Comment by mostafah** [comment]
This PR is now added to [the document](http://w3c.github.io/alreq/). I didn’t close this issue through the commit itself to let others review the changes before that. If it’s fine, this issue can be closed now.

**Comment by behnam** [comment]
We're done here.
