### ISSUE TITLE
Firefox handles (Bidi) closing matching parenthesis the right way

### ISSUE THREAD

**Issue by ntounsi** [w3c/alreq#121]
May be it is already mentioned elsewhere, but Firefox handles a closing matching parenthesis in a Bidi ambiguous situation as it should be, i.e. as a **closing** parenthesis, and not as in UBA (mirrored and misplaced parenthesis). 

Example : the source is "ARABIC ARABIC Internationalisation (I18N) ARABIC ARABIC ..." in RTL base direction

FireFox : 
![ff1](https://cloud.githubusercontent.com/assets/15004708/26735772/db9dde4c-47b2-11e7-957e-002098cb11be.png)

Other browsers (UBA) :
![ff2](https://cloud.githubusercontent.com/assets/15004708/26735807/fa22bee6-47b2-11e7-8a3b-3e81f253a638.png)

It seem as if FF "is aware" that a closing parenthesis has an open parenthesis to match, and it does so. Indeed, when you replace the closing `)` by another unmatched closing sign, say `]`, FF renders the text as UBA.
![ff3](https://cloud.githubusercontent.com/assets/15004708/26735870/3241b87c-47b3-11e7-9585-79a3495e0f7d.png)

I think it is an interesting initiative.
Thoughts?

Shame on other browsers? :-)

**Comment by khaledhosny** [comment]
This is part of the UBA since Unicode 6.3.0 (http://www.unicode.org/reports/tr9/#N0), but not all implementations have been updated. AFAIK it was initially proposed by Microsoft not Mozilla.

**Comment by behnam** [comment]
The UBA got a major update (Revision 29) for Unicode 6.3.0, including Paired Brackets which enable detecting matching pairs in a text and adjusting bidi levels (and mirroring of these characters) accordingly.

As you have noticed, only exact matches work this way, meaning matching `(` and `)` only together, `[` and `]` only together, etc, and a `(` won't match a `]` character.

The Paired Brackets feature, along other new features in the new UBA Revision are not yet available in most of the implementations, as you have observed.

Chrome and other WebKit/Blink-based engines use `FriBidi` (actually, not, but anyways...) which has a longstanding git branch open for it, awaiting fixes and merge into the master and a release. (https://github.com/behdad/fribidi/issues/9) (Ping, @behdad)

Firefox has its own implementation, which I'm not sure about the levels of support for UBA 29, but looks like Paired Brackets is implemented already.

I suppose MS Edge would have the new features as well, but I can't try it out myself. (Please let us know if you find anything about that.)

**Comment by khaledhosny** [comment]
Blink/WebKit do not use FriBiDi AFAIK, they use their own internal implementation. For Blink, suggestion was made for switching to ICU’s implementation but it was not well received by some developers, see https://bugs.chromium.org/p/chromium/issues/detail?id=242238.

**Comment by ntounsi** [comment]
Windows10 Edge and IE11 seem to have this feature also.

**Comment by r12a** [comment]
fwiw, i added some related tests to the i18n test suite
https://www.w3.org/International/tests/repo/results/bidi-algorithm#brackets

**Comment by behnam** [comment]
That's great, @r12a!

Do you think it's worth having tests for the other new feature in 6.3, the isolates?

They still can appear in web text, specially if content produced from plain text, and should be respected when present.

**Comment by r12a** [comment]
@behnam if i understand correctly what you're asking for, you should find those tests just above the ones i pointed to at https://www.w3.org/International/tests/repo/results/bidi-algorithm#rli_etc

**Comment by behnam** [comment]
Yes, that's it! Thanks, @r12a.

**Comment by r12a** [comment]
btw, i have now completed action https://www.w3.org/International/groups/arabic-layout/track/actions/95

**Comment by behnam** [comment]
ACTION is now CLOSED.

**Comment by besfahbod** [comment]
Update: Proper Paired Brackets support and large fixes are coming to Chrome via the LayoutNG backend. See the recent comments on https://bugs.chromium.org/p/chromium/issues/detail?id=302469#c15 for more details.

**Comment by ebraminio** [comment]
LayoutNG solves cross element shaping of Arabic script issue also, see https://bugs.chromium.org/p/chromium/issues/detail?id=939533
