### ISSUE TITLE
Missing terms in glossary

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#130]
Page [372 of Unicode](http://www.unicode.org/versions/Unicode10.0.0/ch09.pdf) core text defines a couple of terms which i was surprised to find missing from the glossary of alreq:

ijam
tashkil

Maybe we should add those, with a condensed description per Unicode.

(Also, there's a gap in the table after mabsut which needs to be fixed.)

**Comment by r12a** [comment]
Actually, harakat and tanwin are also missing. They may also be useful.

Not sure whether we need to add terms like ezafe (Urdu izāfat).

**Comment by behnam** [comment]
A few more terms from Arabic-script Paleography, which I'm not sure if we want to get to, but good to keep track of here:

* Bihari: Writing style used in Chinese and South-East Asia.

* I'jam: (TBD)

* Ihmāl: (TBD)

From <https://ar.wikipedia.org/wiki/%D8%A5%D8%B9%D8%AC%D8%A7%D9%85>:

* الحروف المُهملة: The letters without Noqta'.

* الحروف المُعجمة: The letters with Noqta'.

* حرف الياء: Letter YEH, which sometimes gets Noqta' and sometimes don't.

**Comment by ntounsi** [comment]
@r12a , Ok to add the following terms to the glossary

**Ijam** : Diacritical marks applied to a basic letter shape (or skeleton) to derive a new letter. For example a dot under a "curve" to get the letter Bah.

**Tashkil** :  Marks that are added to letters to  indicate  vocalisation  of  text or  to  correct pronunciation.

**Harakat** : Some (basic) of these vowel marks.

**Tanwin** : (Derived from Noon). An extra Noon pronounced at the end of a word, and indicated by doubling the sign of one of the diacritics Fatha or Damma or Kasra. 

`(Also, there's a gap in the table after mabsut which needs to be fixed.)`

I'll fix it at the same time.

**Comment by ntounsi** [comment]
"Tashkil" is mentioned as "diacritical marks".

**Comment by r12a** [comment]
@ntounsi here are some suggested alterations and a couple of additions.  I think it's useful to mention what are and are not combining characters in Unicode (particularly in case anyone with an IDN background is reading this).

**Ijam** : Diacritical marks applied to a basic letter shape (or skeleton) to derive a new letter. For example a dot under a "curve" to get the letter BEH. In Unicode each letter plus ijam combination is encoded as a separate, atomic character.

**Tashkil** :  Marks that are added to letters to  indicate  vocalisation  of  text or  to  correct pronunciation. In Unicode these are all combining characters applied to a base character.

**Harakat** : Tashkil marks representing short vowel sounds.

**Tanwin** : (Derived from Noon). Tashkil marks indicating postnasalized or long vowels at the end of a word, and indicated by doubling the sign of one of the harakat diacritics. 

**Shadda**: A tashkil mark indicating gemination of the base consonant.

**Sukun**: A tashkil mark indicating the lack of a vowel after the consonant to which it is attached.

wdyt?

**Comment by ntounsi** [comment]
Looks good to me.

**Comment by behnam** [comment]
I'm proposing to add:

* **Ihmāl**: See *Tashkil*.

**Comment by behnam** [comment]
@shervinafshar, the spreadsheet is read to be published again. Thanks!

**Comment by ntounsi** [comment]
I then count on @shervinafshar  for publication.
