### ISSUE TITLE
Review Proposed Draft: Unicode Technical Report #53: Unicode Arabic Mark Ordering Algorithm

### ISSUE THREAD

**Issue by behnam** [w3c/alreq#143]
The draft is available here: http://www.unicode.org/reports/tr53/

> ## Summary
> 
> The Unicode Arabic Mark Ordering Algorithm (UAOA) describes an algorithm for determining
> correct rendering of Arabic combining mark sequences.
> 
> ## OVERVIEW
> 
> The combining classes of Arabic combining characters in Unicode are different than
> combining classes in most other scripts. They are a mixture of special classes for specific
> marks plus two more generalized classes for all the other marks. This has resulted in
> problems for sequences with multiple combining marks since Unicode 2.0.
> 
> UAOA, described herein, is the proposed implementation to deal with the problems of special
> combining classes. This algorithm is the simplest algorithm that matches user expectations,
> stays within the stability requirements of Unicode, correctly renders data in normalized forms,
> and renders all canonically equivalent sequences the same way.

**Comment by behnam** [comment]
@shervinafshar recommended this paper for more background: http://www.iosrjen.org/Papers/vol2_issue12(part-3)/I021234853.pdf

**Comment by behnam** [comment]
Here's my initial feedback:

Any algorithm that's too script-specific—like the algorithm proposed here, applying to only one script—would only create chaos among implementations and users.

If there's a need to fix normalization for some Unicode sequences which is not possible because of the stability promises, a new algorithm may be introduced to replace the old kind-of-broken one, with all the new character properties needed. This has happened to Unicode Identifiers and Unicode Segmentation algorithms already, and therefore can be done for Unicode Normalization as well—if there's a major issue, as it's been claimed by the draft that there is.

**Comment by shervinafshar** [comment]
@behnam, Lazrek et. al. paper I pointed to is not intended for "more background". It's just an earlier try to come up with an algorithm for this purpose.

**Comment by shervinafshar** [comment]
Also, a disclaimer is worth mentioning here that the comments on here are personal opinions of their authors until an official comment is submitted to Unicode via either ALReq or i18n working group.

**Comment by behnam** [comment]
> Lazrek et. al. paper I pointed to is not intended for "more background". It's just an earlier try to come up with an algorithm for this purpose.

As far as I understand, earlier works on some problem is usually looked as the "background" of a more recent work. At least that's what I meant by these words here. If there's another meaning to these words in this context, I'm not familiar with them and they were not my intention.

> Also, a disclaimer is worth mentioning here that the comments on here are personal opinions of their authors until an official comment is submitted to Unicode via either ALReq or i18n working group.

Right. This issue is just an internal discussion to come up with a review for the i18n WG. It's not necessarily on the ALReq TF agenda yet, and again we can decide on that here if we want it to be a TF submission to the WG, or personal feedback and editing for the WG.

That said, feedback from active members of the TF is really appreciated here. @ntounsi, @mostafah, @ebraminio, @khaledhosny.

**Comment by shervinafshar** [comment]
I didn't introduce this paper as background work to TR53. That's what you called it and that's fine, but just wanted to make that clear for the record.

For people who want to send personal comments and opinions regarding the TR, please do it through Unicode PRI: http://blog.unicode.org/2017/09/proposed-draft-utr-53-unicode-arabic.html

**Comment by khaledhosny** [comment]
Here is an example of the issues this proposal is trying to fix https://github.com/behdad/harfbuzz/issues/509 (I had many more with Quranic text, but I need to dig them up).

**Comment by behnam** [comment]
FYI, we are discussing various aspects of this proposal on i18n-activity repo. See the issues filed here:
* https://github.com/w3c/i18n-activity/issues?q=uaoa
* https://github.com/w3c/i18n-activity/issues?q=label:utr53

Since there's now an item for i18n-activity to follow this up, we can decide here if we want to write up a feedback from the ALReq Task Force. Are there any comments about this?

**Comment by shervinafshar** [comment]
> Since there's now an item for i18n-activity to follow this up, we can decide here if we want to write up a feedback from the ALReq Task Force. Are there any comments about this?

Writing up feedback from ALReq seems redundant to me. i18n activity seems a better forum for collection and shaping such feedback. Members of ALReq could decide if they would like to contribute to feedback collected by i18n-activity or submit their feedback individually to Unicode.

As an editor of ALReq, I do not have any comments on UTR#53. As important as it is for Arabic typography, it's a minute detail in the sea of essential stuff we haven't covered yet in our document.

When UTR#53, comes out of PRI and becomes normative, we'll refer to it as common good practice wherever required.

**Comment by r12a** [comment]
The i18n WG is following up on this. The Unicode committee has agreed that this is NOT a new normalization form, nor for resorting stored text in memory, it is a transient operation used during the process of rendering. See https://github.com/w3c/i18n-activity/issues/492#issuecomment-334726159

**Comment by shervinafshar** [comment]
@r12a all received PRIs could be found here: http://www.unicode.org/review/pri359/feedback.html

But I couldn't find the note from UTC in agreement. Sharing it would be beneficial for others' reference.

**Comment by r12a** [comment]
See the new note at the top of the document at http://www.unicode.org/reports/tr53/

> Note​ ​to​ ​reviewers:​ ​This proposed draft UTR makes no change to Unicode normalization
> forms, and does not propose a new normalization form. Instead, this is similar to the
> processing used in https://www.microsoft.com/typography/OpenTypeDev/USE/intro.htm: a
> transient process which is used to reorder text for display in an internal rendering pipeline.
> This reordering is not intended for modifying original text, nor for open interchange.
> Subsequent versions of this document will include this clarification.

**Comment by behnam** [comment]
This matter is being followed by the i18n WG, in separate issues: https://github.com/w3c/i18n-activity/issues?q=label:utr53

Since there's nothing to do here in ALReq about this, let's close this issue and keep the discussion there.
