### ISSUE TITLE
"Font and typographical considerations" Draft

### ISSUE THREAD

**Issue by ntounsi** [w3c/alreq#15]
Hi all,

I just put a draft of the  "font and typographical considerations"  part.
Google docs:
https://docs.google.com/document/d/1IRgcMygoovniN_qL1cjD2WB-FiSyYFKlzEblvJuxRgY/edit?usp=sharing

My (html) working version is at http://www.w3c.org.ma/Tests/Alreq/Font-and-Typographical-considerations.html (or .pdf)
Thank for your comments and suggestions
Najib

**Comment by behnam** [comment]
Looks like a duplicate of #9. We can keep track of converting the text into HTML and putting on Github over there.
