### ISSUE TITLE
Miscellaneous questions and suggestions about list of topics

### ISSUE THREAD

**Issue by mostafah** [w3c/alreq#2]
I’m opening this issue to discuss the ideas and questions about current state of the document.
- Should we also cover the problem of glyph overlap when we talk about joining? Arabic glyphs overlap when they join and this shows itself when applying filters like opacity to a word. The preferred behavior probably is to unify the glyph paths before applying these filters to them.
- Another joining issue that is important in some educational contexts is to style a specific character of a word without breaking its joining.
- Font size is not the only property that could be discussed about mixing scripts (in the line about **Font and Typographical considerations**). Line height and baseline shift are as important.
- The topic of numbering is repeated in different sections and is in fact a requirement for a lot of them. Can we have a unified place in the document that covers numbering in detail and refer to it from other parts like page numbers and lists?

**Comment by behnam** [comment]
@mostafah, would you mind breaking this into four separate issues, and provide example images to open up the discussion?

**Comment by mostafah** [comment]
We now have issues #3, #4, #5, and #6 instead of this.
