### ISSUE TITLE
How to handle transcriptions in the glossary

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#21]
Could we add vowelling to the glossary items?  Not only would this be useful for cases such as   رُقعة vs رِقعة , but it would also help non-native speakers, like me, to know how to pronounce the words.

**Comment by aphillips** [comment]
+1

**Comment by mostafah** [comment]
:+1:, but we have to have a note about why we are doing this, because it’s not a common practice in Persian.

**Comment by ntounsi** [comment]
+1
In general authors vowel some letters, not necessarily all, to disambiguate words when the context don't.
The Quran texts are all voweled.  So are scholar texts.  
Dictionaries entries have vowels also.

**Comment by shervinafshar** [comment]
For Persian, I've already added diacritics when they can help resolve the ambiguity. Having them everywhere would be an overkill for Persian. See the entries for "EM", "EN", "en dash", "em dash", "line head", etc.

**Comment by ntounsi** [comment]
I do the same when it is necessary to put diacritics. See "EM", "Justified alignement" etc.

**Comment by r12a** [comment]
it was agreed during the teleconference to add a transcription column for each language, instead of fully vowelling the glossary keywords, since the latter looks very strange to native speakers (see http://www.w3.org/2015/12/08-alreq-minutes.html#item02).

**Comment by r12a** [comment]
i took an initial stab at providing transcriptions for the Arabic items in the glossary, as much to see how it works as to try to provide help.  What i came up with may need some small corrections (particularly around things like teh marbuta and fathatan, etc.), but hopefully will save some time.  I'm using the LOC rules.

**Comment by ntounsi** [comment]
Thank Richard, for initiating.
I am reviewing... For example

arabic numerals —> arqām ʻarabīat  
s/arabīat/arabīah/

baseline        —> saṭur al-’asāsu
s/saṭur/saṭru/
s/asāsu/asās/

blank page  —> ṣafḥatan fārighah
s/ṣafḥatan/ṣafḥatun/

etc.

**Comment by r12a** [comment]
thanks for the review notes, Najib.  I suggest we continue by email, rather than here.  (Once we have the glossary in the HTML document on github, it will be easy enough to spot differences that we could do this by editing the html, but for now, continuing in this way will probably be better.)  I'll make the changes you suggested so far. [update: ah, i see you have already done so.]

**Comment by ntounsi** [comment]
On 12/15/15 15:29, r12a wrote:

> thanks for the review notes, Najib. I suggest we continue by email, 
> rather than here. (Once we have the glossary in the HTML document on 
> github, it will be easy enough to spot differences that we could do 
> this by editing the html, but for now, continuing in this way will 
> probably be better.) I'll make the changes you suggested so far.

I am doing the changes on the document.

**Comment by r12a** [comment]
On 15/12/2015 15:43, Najib Tounsi wrote:

> On 12/15/15 15:29, r12a wrote:
> 
> > thanks for the review notes, Najib. I suggest we continue by email,
> > rather than here. (Once we have the glossary in the HTML document on
> > github, it will be easy enough to spot differences that we could do
> > this by editing the html, but for now, continuing in this way will
> > probably be better.) I'll make the changes you suggested so far.
> 
> I am doing the changes on the document.

ah, i was hoping to track the changes, so that i can learn from them. 
It's a bit difficult in the google doc.  Oh well.

one question: for مُمتَّن    khaṭun momaṭan

there is no 'o' in LOC transcriptions. So would that sound be best 
represented by 'a' or 'u'?  Presumably the latter?

ri

**Comment by ntounsi** [comment]
On 12/15/15 15:55, r12a wrote:

> On 15/12/2015 15:43, Najib Tounsi wrote:
> 
> > On 12/15/15 15:29, r12a wrote:
> > 
> > > thanks for the review notes, Najib. I suggest we continue by email,
> > > rather than here. (Once we have the glossary in the HTML document on
> > > github, it will be easy enough to spot differences that we could do
> > > this by editing the html, but for now, continuing in this way will
> > > probably be better.) I'll make the changes you suggested so far.
> > 
> > I am doing the changes on the document.
> 
> ah, i was hoping to track the changes, so that i can learn from them.
> It's a bit difficult in the google doc. Oh well.
> 
> one question: for مُمتَّن khaṭun momaṭan

In fact, it was the wrong meaning of "body type". (Unfortunate 
copy/paste from Bold Type)
I changed the translation to الخط الرئيسي Al- khaṭ Al-ra' īs ī

Najib

**Comment by behnam** [comment]
So, let's close this issue and keep the conversation about transliteration schemes (per language) in #16.
