### ISSUE TITLE
Isolation not fully supported — FIXED !

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#215]
Webkit still doesn't apply bidi isolation to an element that has a `dir` attribute (although a shim based on CSS works fine).

This creates significant issues for managing bidirectional text.

(The old Edge still doesn't support directional isolation, but Edge has now moved to Blink, which does support it.)

**Comment by r12a** [comment]
_The first comment in this issue contains text that will automatically appear in [the Arabic & Persian gap-analysis document](https://w3c.github.io/alreq/gap-analysis/) as a subsection with the same title as this issue. Any edits made to that comment will be immediately available in the document. Proposals for changes or discussion of the content can be made in comments below this point._

**Comment by fantasai** [comment]
Fixed by Myles in https://bugs.webkit.org/show_bug.cgi?id=134630 !

**Comment by r12a** [comment]
Webkit does now support this.  Test results and links to tests can be found at https://w3c.github.io/i18n-tests/results/the-dir-attribute-isolation

Therefore, this issue can be closed.
