### ISSUE TITLE
Several images 404ing in main text

### ISSUE THREAD

**Issue by owenblacker** [w3c/alreq#246]
When I visit https://www.w3.org/TR/alreq/, there are several images showing as broken; telling my browser to load them gets me a 404, such as [differentInitialNoon.jpg](https://www.w3.org/TR/alreq/images/differentInitialNoon.jpg).

These load correctly when I access an old version of the doc from the Internet Archive, such as this [2018-03-09 snapshot](https://web.archive.org/web/20180309221300/https://www.w3.org/TR/alreq/).

شكرًا!

**Comment by r12a** [comment]
Thanks for the report !

I'll look into it.

**Comment by r12a** [comment]
Should now be fixed. Thanks again for reporting.  Reopen this if you still have problems.

**Comment by owenblacker** [comment]
It is indeed. Thank you @r12a 💖
