### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by xfq** [w3c/alreq#273]
https://www.w3.org/TR/alreq/#h_origins

> The Arabic script belongs to the class of Semitic writing systems. It evolved from the Nabatean script, and attained its distinctive form by the 4th century CE. It is closely related to the Syriac and the Hebrew script. The earliest attested document written in the Arabic alphabet in its classical form stems from the Islamic era, it is dated to 643 CE.

"Nabatean" should probably be "Nabataean"?

**Comment by shervinafshar** [comment]
Thanks for the suggestion. Even though both spelling seem common, but Unicode, Omniglot, and Britannica 1911 prefer "Nabataean". I have updated the document with your suggestion.
