### ISSUE TITLE
Drafting “direction”

### ISSUE THREAD

**Issue by mostafah** [w3c/alreq#28]
I have a draft [here in Google Drive](https://docs.google.com/document/d/177yHWJ9WZLDyekFioxFPOrmycN-76ueXnQ2jrucxh3w/edit?usp=sharing). This is very short, because the role of this section is to introduce the direction of the Arabic script briefly and introduce references for further reading and I couldn’t think of more information to put here. If you have any suggestions for what can be added here, please leave a comment.

**Comment by r12a** [comment]
i think we should move this into the main document.  (I added some text to the Google doc which you can accept or delete.)

**Comment by mostafah** [comment]
Sorry if you wanted to expand on this and waited too long. Sent the PR: #40.

**Comment by r12a** [comment]
To be done: a simple overview of the bidi algorithm.

**Comment by r12a** [comment]
Here's a link to the existing description: 
https://www.w3.org/International/articles/inline-bidi-markup/uba-basics

**Comment by mostafah** [comment]
I finished the text, but the images are not done yet. The text is available at [the same Google Drive document](https://docs.google.com/document/d/177yHWJ9WZLDyekFioxFPOrmycN-76ueXnQ2jrucxh3w/edit?usp=sharing).

I’ll send a PR after I’ve made the images. You can review the text in the meantime.

**Comment by r12a** [comment]
@mostafah looks good!  I suggested a few trivial editorial edits in the doc.

**Comment by mostafah** [comment]
@r12a Thanks for the review and the speed.

**Comment by mostafah** [comment]
Moved the draft to [a wiki page](https://github.com/w3c/alreq/wiki/Draft-for-“2.3-Direction”) for further discussion.

**Comment by mostafah** [comment]
A few weeks ago we discussed the confusion over “logical order” and “visual order.” I updated that part of [the draft](https://github.com/w3c/alreq/wiki/Draft-for-“2.3-Direction”) with what I hope is a simpler explanation of the concept. The change is in the first image and its two preceding paragraphs.

Is this new version any better? More suggestions?

**Comment by ntounsi** [comment]
Figure 1
s/memroy/memory/

Paragraph before last:
May be mention also weak directional property for numerals.

About logical order, I wonder if it's worth to mention why it is "a pain" to work only in visual order. Problems such as writing the text backwards, line wrapping, explicitly right-align text in paragraphs etc.

**Comment by mostafah** [comment]
Thanks for the catch. Updated the image.

I understand the importance of weak directions, but I’m worried it might make this section even more complicated. I know it will be helpful for some curious readers, but I don’t know whether it will be worth it or not. What’s your opinion on this?

I have the same concern about mentioning why we don’t store text in the visual/display order. I thought about adding a sentence like that myself, but then skipped it assuming few people would have that question.

**Comment by ntounsi** [comment]
I share your worry to keep things simple and not go into the technical details, which can be found in external references.

**Comment by r12a** [comment]
Editorial suggestion: I think the text in figure 1 "The order of characters in memory" should be the caption, and the text "The order of the same characters when displayed" should also be a caption (which of course, means splitting Figure 1 into two figures).  As a general rule, i think we should avoid text in graphics where possible, and it seems possible here.
