### ISSUE TITLE
Mentioning glyph overlap behavior, specially with effects

### ISSUE THREAD

**Issue by mostafah** [w3c/alreq#3]
Arabic glyphs have overlap when they join. This shows itself in an unwelcome form in some contexts, like when opacity or text border is applied to texts.

The following image demonstrates this problem: glyph joins should not be seen (like in the “normal” text), but they become visible when transparency or text border is applied in a poor implementation.

![glyph overlap](https://cloud.githubusercontent.com/assets/531910/10455300/4d171804-71c7-11e5-9da6-f2a8192796a7.png)

A proper implementation would unify glyph paths into a single one before applying these filters. This is what the correct rendering would result in:

![glyph overlap - proper](https://cloud.githubusercontent.com/assets/531910/10455669/791ed390-71c9-11e5-8c41-b1b27ac60728.png)

Is this something we should mention as a requirement?

**Comment by r12a** [comment]
i would be inclined to add this information.  It's an interesting issue that arises due to the cursive nature of the script.

**Comment by mostafah** [comment]
I agree. I guess the right place to talk about this in our current list of topics is “Arrangement and Joining Behavior”, where we discuss the issues that arise when dealing with joining.

**Comment by r12a** [comment]
i agree

**Comment by behnam** [comment]
Needs drafting and to be added to 3.1. Arrangement and Joining Behaviour section.
