### ISSUE TITLE
Drafting questions

### ISSUE THREAD

**Issue by r12a** [w3c/alreq#38]
I have made a start on my action to draft questions to help prompt completion of the main sections of the document.  Before adding more, i'd like feedback on the approach i'm using, to check that i'm not going in the wrong direction.

You can see a version of the document with the new text at:
http://htmlpreview.github.io/?https://github.com/r12a/alreq/blob/af96cf655a38948746d0267d7b5fb5c77f818787/index.html

Fwiw, the diff is at:
https://github.com/r12a/alreq/commit/af96cf655a38948746d0267d7b5fb5c77f818787

**Comment by mostafah** [comment]
LGTM

This seems like a right move and can help us in drafting those sections.

But the diff is more than just a single change. It would be better to have each PR/diff/… focused on a single purpose.

**Comment by r12a** [comment]
> But the diff is more than just a single change. It would be better to have each PR/diff/… focused on a single purpose.

In principle, i agree. In this case i'd like to negotiate an exception on the grounds that this is first draft material that doesn't impinge on or change any existing parts of the text.  I brought it up with Shervin on Tuesday, and he said i should go ahead and send a PR, which i'll do now.
