### ISSUE TITLE
It should be possible to style a single character without breaking Arabic joining

### ISSUE THREAD

**Issue by mostafah** [w3c/alreq#4]
It is sometimes a requirement in educational texts to style a single character of a word. This requires putting that single character (or a small group of successive characters) in a new group. This should not lead to broken joining.

This image compares the expected behavior with what may be achieved in a poor implementation:

![glyph styling](https://cloud.githubusercontent.com/assets/531910/10455908/0f718a76-71cb-11e5-8c02-f27700a2021d.png)

**Comment by behnam** [comment]
Needs drafting and to be added to 3.1. Arrangement and Joining Behaviour section.
