### ISSUE TITLE
Symbols in the language columns of the character tables are confusing

### ISSUE THREAD

**Issue by mostafah** [w3c/alreq#52]
Several people have found the ●, ○, and ✕ characters confusing. They should be replaced with better alternatives.

**Comment by mostafah** [comment]
Repo admins can label it as “future.” At least IMO it’s not a priority right now.

**Comment by mostafah** [comment]
I’ve found some Emoji characters for this, but since this is subjective and I am not completely confident about these choices, I’d like to know your opinion as well:

- [❎](http://emojipedia.org/negative-squared-cross-mark/): The character is not used in the language.
- [✅](http://emojipedia.org/white-heavy-check-mark/): The character is used in the language.
- [✳️️](http://emojipedia.org/eight-spoked-asterisk/): This is an auxiliary character for the language.

What do you think? Any other suggestions?

**Comment by mostafah** [comment]
To get a better feel about these, I put them in the tables to see [what the result will be](http://static.kolah.ir/alreq/#characters-tables).

**Comment by behnam** [comment]
I agree with the need to fix the problem, but the new characters used are a bit too system-dependent, specially becoming Emoji-style in some context, and Text-style in some other.

This is was I see from the test (static.kolah.ir) you shared, @mostafah:

![image](https://cloud.githubusercontent.com/assets/37169/22195184/83718b1a-e0fb-11e6-8812-29c6b1bd64d6.png)

Maybe we can just go with ASCII letters/numbers, like { X, A, B }, A and B being groups defined, or { X, 1, 2 }, 1 and 2 being like *degree* of importance/relativity/etc?

**Comment by mostafah** [comment]
Yes. That’s a problem with emojis. I thought about character codes too, but was worried that they are not very intuitive and easy to remember. N/Y/A (no, yes, auxiliary) might be better than the codes.

**Comment by r12a** [comment]
My 2p: for me, the main problem with the green icons is that it's hard to spot, say, the crosses, since the green box is the same.  In that respect, the fallback's Behnam is seeing above are actually better, although it would be even clearer if we were able to use different colours in addition to different shapes.

**Comment by mostafah** [comment]
I looked for a red emoji for the cross, but could not find one. There is ❌, but it does not have matching emojis for our two other cases.

But we can easily color non-emoji symbols, like red ✕ and green ✓ and ✶.

**Comment by mostafah** [comment]
[Updated the preview with the new suggestion](http://static.kolah.ir/alreq/#characters-tables).

**Comment by ntounsi** [comment]
+1
Looks better and is Emoji independent.
