### ISSUE TITLE
Proper tags for titles: H2 or H3?

### ISSUE THREAD

**Issue by mostafah** [w3c/alreq#69]
Related to our recent cleanup changes to the document, I noticed that we are not consistent about the HTML tags for titles.

Most of the document uses `h2` for all levels of headers, depending on nested `section`s for building hierarchy, but we also have some `h3`s in similar situations.

Is this something that we should care about? And if so, what is the suggested solution? I can send a PR if we have a policy for this.

**Comment by r12a** [comment]
i noticed that in the toc 2.4.4's title was unexpectedly bolded, but i haven't had time to investigate.

i think we should go through and ensure that all hx elements are the correct ones.

**Comment by mostafah** [comment]
That’s something else. That is because we have this code there:

```
<h3><span style="font-weight: bold;">Fonts</span></h3>
```

**Comment by mostafah** [comment]
I took a look at [ReSpec’s User’s Guide](https://github.com/w3c/respec/wiki/User's-Guide#sections). Any of `h1`–`h6` would work, because ReSpec changes them based on section level, but using one is a good habit. ReSpec says

> Using `h2` everywhere is sort of a tacit convention, but if you prefer `h5` that'll work just the same.

So, I guess having `h2` everywhere is good. Will send a quick PR for that. We can still discuss if you suggest otherwise.

**Comment by r12a** [comment]
yes, we could do that, but that relies on respec to sort things out.  I think it's better to use the appropriate heading for the appropriate section.  For example, when editing in DreamWeaver, i don't get the benefit of respec's javascript, and it helps a lot to make the text more readable if the range of hx elements are used.

**Comment by mostafah** [comment]
PR #71 fixes both of the above: the bold style for 2.4.4 and using `<section><h2>` everywhere.

But I noticed two other issue: One is a few of our `<section>`s don’t have `id`s. I’ll fix that by adding ID for them.

Another is that some of our titles are linked to their own sections and some are not. Compare [2.3 Joining](http://w3c.github.io/alreq/#h_joining) with [2.4 Font and Typographical considerations](http://w3c.github.io/alreq/#h_font_and_typographical_considerations) to see the difference. Which is preferred? ReSpec does not use or discuss links for titles, so I guess I can remove them?

**Comment by ntounsi** [comment]
On 14/09/16 19:47, r12a wrote:

> i noticed that in the toc 2.4.4's title was unexpectedly bolded, but i 
> haven't had time to investigate.

Yes. Unexpected bold. I'll remove it at the next PR.

**Comment by ntounsi** [comment]
We have :
1)  `h3` in nested subsection with `href` to parent `h2` section id
 `<section id="h_characters_and_words">

```
 <h2><a href="#h_characters_and_words">Characters and Words</a></h2>

   <section id="h_diacritics">

    <h3><a href="#h_diacritics">Diacritics</a></h3>
```

`

2) `h3` in nested subsection **without** `href` to parent `h2` section id

`<section id="h_font_and_typographical_considerations">

```
<h2><a href="#h_font_and_typographical_considerations">Font and Typographical considerations</a></h2>

     <section id="h_arabic_style_and_calligraphy">
       <h3>Arabic Style and Calligraphy</h3>
     ...

      <section id="h_different_writing_styles">
        <h3>Different Writing Styles</h3>
```

`

3)  `h3` under `h2` but not in subsection
 `<section class="appendix" id="characters-tables">

```
<h2>Characters</h2>

   <p>The following tables [...] or that langauge.</p>

     <h3>Alphabetical characters</h3>
        ...
     <h3>Diacritics</h3>
```

`

I guess case 1) is the best choice

**Comment by mostafah** [comment]
@ntounsi, You don’t have to change these. I’ve already removed the bold font and did other changes. It’ll be in the repo when we merge the PR.

Since both of you are in favor of using `h3`… for subsections, I keep that as our agreement. I’ll update the PR.

What about linking headings to their own sections? Najib is suggesting to use them. I don’t, because they are not doing very much (links are available in ToC) and the headers look better without them. Other opinions?

**Comment by shervinafshar** [comment]
I don't think there is a clear purpose for the "link to self" for the sections. As long as we can link to sections in the URL (which Mostafa mentioned is possible via ReSpec default behaviour), we should be good. We can get rid of these redundant tags.
