### ISSUE TITLE
ACTION-63: Provide sources and urls for the images 

### ISSUE THREAD

**Issue by ntounsi** [w3c/alreq#73]
Hi,

Here are the source links for the images (see bellow [1])
For most of them, the Commun wikimedia page proposes how to use the images. With at least a href to "the page URL" and a src to the "file URL". There is also an "attribution", but "not not legally required"

Two questions arise :
1) Should the document link the images to their source page?
2) Should we keep the image locally (`src = "images/..."`) or point to them at wikimedia (`src = "_the origine at wikipedia_"`) ?

[1]
Kufic script
src = https://upload.wikimedia.org/wikipedia/commons/b/b6/A_section_of_the_Koran_-_Google_Art_Project.jpg
href = https://commons.wikimedia.org/wiki/File:A_section_of_the_Koran_-_Google_Art_Project.jpg

Thuluth script
src = https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Basmalah-1wm.png/220px-Basmalah-1wm.png
href = https://commons.wikimedia.org/wiki/File:Basmalah-1wm.png

Naskh script
src = https://upload.wikimedia.org/wikipedia/commons/8/83/FirstSurahKoran_%28fragment%29.jpg
href = https://commons.wikimedia.org/wiki/File:FirstSurahKoran_%28fragment%29.jpg

Ruq'ah script
src = https://upload.wikimedia.org/wikipedia/fa/f/f9/Ruq_ah.gif
href = https://fa.wikipedia.org/wiki/پرونده:Ruq_ah.gif

Taaliq
src = https://upload.wikimedia.org/wikipedia/commons/d/df/Miremad-1.jpg
href = https://commons.wikimedia.org/wiki/File:Miremad-1.jpg

Diwani script
src = https://upload.wikimedia.org/wikipedia/commons/0/01/Izzet_44.png
href = https://commons.wikimedia.org/wiki/File:Izzet_44.png

Nasta'liq script
src = https://upload.wikimedia.org/wikipedia/commons/9/9b/Khatt-e_Nastaliq.jpg
href = https://commons.wikimedia.org/wiki/File:Khatt-e_Nastaliq.jpg

Maghribi script
src = https://upload.wikimedia.org/wikipedia/commons/3/35/Maghribi_script_sura_5.jpg
href = https://commons.wikimedia.org/wiki/File:Maghribi_script_sura_5.jpg

**Comment by shervinafshar** [comment]
@ntounsi will kindly create a PR updating these in the document and adding the reference information for the Wikipedia pages.
