### ISSUE TITLE
Drafting "Characters in Use"

### ISSUE THREAD

**Issue by shervinafshar** [w3c/alreq#8]
@mostafah started a draft for "Characters in Use" topic keyword. The initial draft can be found in [here](https://docs.google.com/document/d/1uPrxdtedlodiabT4SjptfVqumeHJCe8Pkl8eWXFiFJc/edit?ts=56389689#).

We're going to discuss the draft here and add the content to the Google Doc.

**Comment by mostafah** [comment]
For the record, @r12a added two points about this in the mailing list:
- We could probably start with the characters indicated for Arabic and Persian in CLDR and if we deviate from the CLDR lists we should probably feed back that information to CLDR, if appropriate.
- We should scope this section to include only Arabic and Persian languages and make that clear in the introductory text.

I totally agree with the first one. The current tables were built quickly just to be able to talk about correct structure and presentation for these data.

I also agree that we should score this section to Arabic and Persian, but if that is mentioned in the introduction section of the document repeating it under other sections might not be necessary.

**Comment by mostafah** [comment]
I added some explanation about diacritics and control characters to the text.

**Comment by khaledhosny** [comment]
Re image 1: I think the choice of karsa to combine with shadda is problematic, given that placing the kasra below the base even when shadda is present is a legitimate choice (and is even preferred by some). We should either clarify this or choose a different combination.

**Comment by mostafah** [comment]
That’s a fair point. The advantage of using kasra is that it is visually very clear that something has changed when combined with shadda, but I guess I can find a way to show the issue with other diacritical combinations.

**Comment by r12a** [comment]
btw, note that the NFC order of characters is

  ‎0628  ARABIC LETTER BEH
  ‎0650  ARABIC KASRA
  ‎0651  ARABIC SHADDA

so i think we should probably follow that order in the example, just to (even slightly, or subliminally) encourage use of NFC ordering in content.

**Comment by mostafah** [comment]
@khaledhosny I tinkered with different ways of visualizing this concept, but none of them was as obvious and easy as moving kasra above the case. I checked Unicode’s example to get more ideas, but they were doing the same too. What‘s your opinion about not changing the picture, but just noting that this only an example, not a suggestion?

**Comment by mostafah** [comment]
@r12a Good catch. I changed the image.

**Comment by khaledhosny** [comment]
I think it is fine to use it as example, but point out that this is not its only behaviour.

**Comment by mostafah** [comment]
@khaledhosny I changed the sentence that refers to the image as an example. Is this good enough?

**Comment by khaledhosny** [comment]
Sounds good.

**Comment by shervinafshar** [comment]
Waiting for the charts to finalize.

**Comment by mostafah** [comment]
@shervinafshar Yes, that’s issue #31.
